### ISSUE TITLE
Difido crash: Failed to get status of the elastic index 

### ISSUE THREAD

**Issue by itay85** [Top-Q/difido-reports#133]
Version = 2.1.00
2017-04-26 18:14:02.170  WARN 784 --- [.0-8080-exec-10] i.c.t.r.business.elastic.ESController    : Total number of shards (4) is not equal to the number of successful shards (2). Check that all nodes are available

2017-04-27 13:44:22.864 ERROR 784 --- [.0-8080-exec-10] i.c.t.r.business.elastic.ESController    : Failed to get the status of the Elatic index
2017-04-27 13:44:22.864 ERROR 784 --- [.0-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at il.co.topq.report.business.elastic.ESController.validateElasticStatus(ESController.java:89) ~[difido-server.jar!/:2.1.00]
        at il.co.topq.report.business.elastic.ESController.saveDirtyTests(ESController.java:216) ~[difido-server.jar!/:2.1.00]
        at il.co.topq.report.business.elastic.ESController.onMachineCreatedEvent(ESController.java:211) ~[difido-server.jar!/:2.1.00]
        at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:227) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:144) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:106) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]

my elastic info  : 
{
  "cluster_name" : "elasticsearch",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 33,
  "active_shards" : 33,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 33,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 50.0
}

**Comment by itaiag** [comment]
Hi. 
It seems that there is a connectivity problem between the server and the Elasticsearch. The current log is not enough informative for debugging the problem. I've create a more informative version that can be downloaded from [this link](http://maven.top-q.co.il/content/repositories/snapshots/il/co/topq/report/difido-server/2.1.01-SNAPSHOT/difido-server-2.1.01-20170427.130952-3.zip), and I will appreciate if you could reproduce the problem with this version and attach the errors in the log to this thread.

**Comment by itay85** [comment]
Thanks , Will install this and report back

**Comment by itay85** [comment]
Since installing the new difido with new logs problem did not reproduced. 
I will keep monitoring to see when issue is reproduce and will attach logs if so

**Comment by itaiag** [comment]
Thanks for the update. 

Closing the issue until/if it is reproduced.
